#include "require.hpp"

WiFiUDP ntpUDP;

LiquidCrystal_I2C lcd(0x27, 20, 4);
NTPClient timeClient(ntpUDP, NTPSERVER, NTPOFFSET);
MFRC522 rfid(SS_PIN, RST_PIN);

bool runprogram = false;
const char html[] PROGMEM = "<!DOCTYPE html><html lang='id'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Konfigurasi NodeMCU</title><style>*{margin:0;padding:0;box-sizing:border-box;font-family:Arial,sans-serif}body{background:#f8f9fa;padding:20px;display:flex;justify-content:center;align-items:center;min-height:100vh}.container{max-width:400px;margin-top:50px;background:#fff;padding:20px;border-radius:10px;box-shadow:0 0 10px rgba(0,0,0,.1);width:100%}.text-center{text-align:center;margin-bottom:20px}.form-group{margin-bottom:12px}.form-label{display:block;margin-bottom:6px;font-weight:500}.form-control{width:100%;padding:8px;border:1px solid #ced4da;border-radius:4px;font-size:14px;transition:.15s}.form-control:focus{border-color:#86b7fe;outline:0;box-shadow:0 0 0 3px rgba(13,110,253,.25)}.btn{display:block;width:100%;padding:10px;font-size:14px;border-radius:4px;cursor:pointer;border:none;font-weight:bold}.btn-primary{color:#fff;background:#0d6efd}.btn-primary:hover{background:#0b5ed7}.btn-primary:disabled{opacity:.65;cursor:not-allowed}.alert{display:none;padding:10px;border-radius:4px;margin-top:12px}.alert-success{background:#d1e7dd;color:#0f5132;border:1px solid #badbcc}</style></head><body><div class='container'><h3 class='text-center'>Konfigurasi NodeMCU</h3><form id='configForm'><div class='form-group'><label for='ssid' class='form-label'>WiFi (SSID)</label><input type='text' class='form-control' id='ssid' required></div><div class='form-group'><label for='password' class='form-label'>Password</label><input type='password' class='form-control' id='password' required></div><div class='form-group'><label for='nodered' class='form-label'>Node-RED</label><input type='url' class='form-control' id='nodered' placeholder='http://IP:PORT/absensi' required></div><button type='submit' class='btn btn-primary'>Simpan</button></form><div class='alert alert-success' id='successMsg'>✅ Konfigurasi berhasil disimpan!</div></div><script>document.getElementById('configForm').addEventListener('submit',e=>{e.preventDefault();let t=new FormData(e.target),o=new URLSearchParams(t).toString(),n=document.querySelector('.btn-primary');n.innerText='Menyimpan...',n.disabled=!0,fetch('/save',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:o}).then(e=>{e.ok&&(document.getElementById('successMsg').style.display='block',setTimeout(()=>location.reload(),3e3))}).catch(e=>console.error('Gagal menyimpan:',e)).finally(()=>{n.innerText='Simpan',n.disabled=!1})});</script></body></html>";